apiVersion : apps/v1
kind: Deployment
metadata:
  name: "myakscluster-ef68"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "myakscluster-ef68"
  template:
    metadata:
      labels:
        app: "myakscluster-ef68"
    spec:
      containers:
        - name: "myakscluster-ef68"
          image: "anilbhatbcr.azurecr.io/myakscluster"
          ports:
          - containerPort: 80